name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Tests
        run: ./gradlew test

      - name: Pull latest Docker image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}

      - name: Recreate Docker container
        run: |
          docker stop member-profile-ui || true
          docker rm member-profile-ui || true
          docker run -d --name member-profile-ui -p 8000:8000 ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}
