name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build, Test, and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Tests and Coverage
        run: |
          ./gradlew clean test jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/
