ktor {
    development = true
    development = ${?DEV_MODE}
    deployment {
        port = 8081
        port = ${?PORT}
    }
}
app {
    use-mock-services = true
    use-mock-services = ${?USE_MOCK_SERVICES}
    discourse {
        apiKey = "dummy-secret-for-dev"
        apiKey = ${?DISCOURSE_API_KEY}
    }
    db {
        url = "jdbc:mariadb://localhost:3306/member_profile"
        url = ${?DB_URL}
        user = "member-profile-user"
        user = ${?DB_USER}
        password = "dummy-password-for-dev"
        password = ${?DB_PASSWORD}
    }
    api {
        key = "dummy-key-for-dev"
        key = ${?API_KEY}
        client = "member-profile-ui"
        client = ${?API_CLIENT}
    }
    ldap {
        host = "localhost"
        host = ${?LDAP_HOST}
        port = 389
        port = ${?LDAP_PORT}
        user = "cn=admin,dc=dms,dc=local"
        user = ${?LDAP_USER}
        password = "Adm1n!"
        password = ${?LDAP_PASSWORD}
    }
    logging {
        level = "debug"
        level = ${?ENV_LOG_LEVEL}
        elastic-host = "localhost"
        elastic-host = ${?ENV_ELASTIC_HOST}
        elastic-api-key = "dummy-key-for-dev"
        elastic-api-key = ${?ENV_ELASTIC_API_KEY}
    }
}