http:
  routers:
    ui:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: ui-weighted
  services:
    ui-weighted:
      weighted:
        services:
          - name: "ui-blue@docker"
            weight: 100
          - name: "ui-green@docker"
            weight: 0
