ktor {
  development = true
    development = ${?ENV_DEV_MODE}
  deployment {
    port = 8000
    port = ${?ENV_PORT}
  }
}

app {
  base-url = "http://localhost:8000"
  base-url = ${?ENV_BASE_URL}
  oidc {
    authorize-url = "http://localhost:8080/realms/DMS/protocol/openid-connect/auth"
    authorize-url = ${?ENV_AUTHORIZE_URL}
    access-token-url = "http://localhost:8080/realms/DMS/protocol/openid-connect/token"
    access-token-url = ${?ENV_ACCESS_TOKEN_URL}
    client-id = "member-profile"
    client-id = ${?ENV_CLIENT_ID}
    client-secret = "dummy-secret-for-dev-mode"
    client-secret = ${?ENV_CLIENT_SECRET}
    sso-profile-url = "http://localhost:8080/realms/DMS/account/"
    sso-profile-url = ${?ENV_SSO_PROFILE_URL}
    user-info-url = "http://localhost:8080/realms/DMS/protocol/openid-connect/userinfo"
    user-info-url = ${?ENV_USER_INFO_URL}
  }
  discourse {
    sso-secret = "dummy-secret-for-dev-mode"
    sso-secret = ${?ENV_DISCOURSE_SSO_SECRET}
    redirect-url = "http://localhost:8000/discourse-callback"
    redirect-url = ${?ENV_DISCOURSE_REDIRECT_URL}
  }
  member-service {
    url = "http://localhost:8081"
    url = ${?ENV_SERVICE_URL}
    api-key = "dummy-key-for-dev"
    api-key = ${?ENV_SERVICE_API_KEY}
    api-client = "member-profile-ui"
    api-client = ${?ENV_SERVICE_API_CLIENT_ID}
  }
  logging {
    level = "debug"
    level = ${?ENV_LOG_LEVEL}
    elastic-host = "localhost"
    elastic-host = ${?ENV_ELASTIC_HOST}
    elastic-api-key = "dummy-key-for-dev"
    elastic-api-key = ${?ENV_ELASTIC_API_KEY}
  }
}