ktor {
  deployment {
    port = 8000
    port = ${?ENV_PORT}
  }
  application {
    modules = [
      "org.dallasmakerspace.thymeleaf.server.ThymeleafKtorApplicationKt.main"
    ]
  }
}

app {
  base-url = "http://localhost:8000"
  base-url = ${?ENV_BASE_URL}
  oidc {
    authorize-url = "http://localhost:8080/realms/DMS/protocol/openid-connect/auth"
    authorize-url = ${?ENV_AUTHORIZE_URL}
    access-token-url = "http://localhost:8080/realms/DMS/protocol/openid-connect/token"
    access-token-url = ${?ENV_ACCESS_TOKEN_URL}
    client-id = "member-profile"
    client-id = ${?ENV_CLIENT_ID}
    client-secret = "dummy-secret-for-dev-mode"
    client-secret = ${?ENV_CLIENT_SECRET}

  }
}