# Use eclipse temurin JDK 21 as the base image
FROM maven:3-eclipse-temurin-21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY build/libs/member-profile-ui-all.jar app.jar

# Expose the port the application runs on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]
